
security:
  oauth2:
    client:
      client-id: app-two
      client-secret: 123
      user-authorization-uri: http://127.0.0.1:9900/server/oauth/authorize
      access-token-uri: http://127.0.0.1:9900/server/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:9900/server/oauth/token_key
server:
  port: 9902
  servlet:
    context-path: /app2